# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [2]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
#%pip install --upgrade selenium
#%pip install webdriver-manager

#### Passo 2: Importar bibliotecas

In [3]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para gerenciar o serviço do ChromeDriver (processo em segundo plano que controla o Chrome)
# - Iniciar/parar o ChromeDriver
# - Configurar opções de execução
# - Gerenciar portas e processos
# - Definir caminhos do executável
from selenium.webdriver.chrome.service import Service 

# Módulo para gerenciamento do ChromeDriver:
# - Baixa automaticamente a versão correta do ChromeDriver
# - Verifica e atualiza drivers desatualizados
# - Elimina a necessidade de baixar manualmente o driver
# - Gerencia compatibilidade de versões
from webdriver_manager.chrome import ChromeDriverManager 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [4]:
#driver = webdriver.Chrome(service=Service(ChromeDriverManager().install())) 
driver = webdriver.Chrome()

#### Passo 4: Acessar site

In [5]:
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### Passo 5: Fechar navegador

In [6]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [7]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### 6.2: Selecionar o campo de busca pelo id

In [8]:
campo_busca = driver.find_element(By.ID, 'id_term')

#### 6.3: Escrever um texto no campo de busca

In [9]:
campo_busca.send_keys('Irlen Syndrome')

#### 6.4: Clicar no Botão Pesquisar

In [10]:
driver.find_element(By.CLASS_NAME, 'search-btn').click()

#### 6.5: Fechar navegador

In [11]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [12]:
# Criar navegador e acessar site
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

# Selecionar o campo de busca pelo id
campo_busca = driver.find_element(By.ID, 'id_term')

# Escrever um texto no campo de busca + Enter para iniciar busca
campo_busca.send_keys('Irlen Syndrome', Keys.ENTER)

# Listar todos os resultados
resultados = driver.find_elements(By.CLASS_NAME, 'full-docsum') # Atenção para a função find_elements (no plural)
print('Total de resultados:', len(resultados))

Total de resultados: 10

#### 7.1: Listar o título de todos os resultados

In [13]:
lista_de_titulos = []
for i in resultados:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, 'docsum-title').text)   
lista_de_titulos

['Irlen syndrome: systematic review and level of evidence analysis.',
 'Dizziness in a Child With Irlen Syndrome: Differentiating Visual and Vestibular Complaints.',
 'Dyslexia with and without Irlen syndrome: A study of influence on abilities and brain-derived neurotrophic factor level.',
 '[The Irlen syndrome--are there pathophysiologic correlates and scientific evidence for "reading with colors"?].',
 'Specific visual symptoms and signs of Meares-Irlen syndrome in Korean.',
 'Functional magnetic resonance imaging findings in Meares-Irlen syndrome: a pilot sudy.',
 'Irlen syndrome: expensive lenses for this ill defined syndrome exploit patients.',
 'Plasma cholesterol levels and Irlen syndrome: preliminary study of 10- to 17-yr.-old students.',
 'Irlen lenses: a critical appraisal.',
 'Optometric correlates of Meares-Irlen syndrome: a matched group study.']

#### 7.2: Listar o link de todos os resultados

In [14]:
lista_de_links = []
for j in resultados:
    link = j.find_element(By.CLASS_NAME, "docsum-title").get_attribute("href")
    lista_de_links.append(link)

lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/30970133/',
 'https://pubmed.ncbi.nlm.nih.gov/31469774/',
 'https://pubmed.ncbi.nlm.nih.gov/37786524/',
 'https://pubmed.ncbi.nlm.nih.gov/14694847/',
 'https://pubmed.ncbi.nlm.nih.gov/24688259/',
 'https://pubmed.ncbi.nlm.nih.gov/25829829/',
 'https://pubmed.ncbi.nlm.nih.gov/25239616/',
 'https://pubmed.ncbi.nlm.nih.gov/14738334/',
 'https://pubmed.ncbi.nlm.nih.gov/2136527/',
 'https://pubmed.ncbi.nlm.nih.gov/8524579/']

#### 7.3: Acessar um dos links

In [15]:
# Por exemplo o link listado na primeira posição da lista_de_links
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

##### 1) Título

In [18]:
titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
print('Título:', titulo)

Título: Irlen syndrome: systematic review and level of evidence analysis

##### 2) Autores

In [17]:
# Autores
try:
    autores = driver.find_element(By.CLASS_NAME, 'authors-list').text
except:
    # Alternativa: juntar nomes individuais
    autores_els = driver.find_elements(By.CLASS_NAME, 'full-name')
    autores = ', '.join([a.text for a in autores_els])
print('Autores:', autores)

Autores: Jordan Da Silva Miyasaka  1 , Raphael V Gonzaga Vieira  1 , Elaine Shizue Novalo-Goto  1 , Erik Montagna  1 , Rubens Wajnsztejn  1

##### 3) Ano de publicação

In [ ]:
try:
    # Exemplo típico: "Front Psychol. 2019 Mar 22;10:435."
    citacao = driver.find_element(By.CLASS_NAME, 'cit').text
    # Extrai o primeiro número de 4 dígitos (ano)
    import re
    ano_match = re.search(r'\b(19|20)\d{2}\b', citacao)
    ano = ano_match.group(0) if ano_match else citacao
except:
    # Fallback: meta tag ou outro seletor
    try:
        ano = driver.find_element(By.CSS_SELECTOR, 'meta[name="citation_publication_date"]').get_attribute('content')
    except:
        ano = 'Não encontrado'
print('Ano de publicação:', ano)

Ano de publicação: 2019

##### 4) DOI

In [ ]:
try:
    doi_el = driver.find_element(By.CSS_SELECTOR, 'a[data-ga-action="DOI"]')
    doi = doi_el.text.strip()
except:
    try:
        # Alternativa comum
        doi_el = driver.find_element(By.CLASS_NAME, 'id-link')
        doi = doi_el.text.strip()
    except:
        try:
            doi = driver.find_element(By.CSS_SELECTOR, 'meta[name="citation_doi"]').get_attribute('content')
        except:
            doi = 'Não encontrado'
print('DOI:', doi)

DOI: 10.1590/0004-282X20190014

##### 5) Tipo de publicação

In [ ]:
try:
    tipos = driver.find_elements(By.CLASS_NAME, 'publication-type')
    tipo = ', '.join([t.text for t in tipos]) if tipos else 'Não informado'
except:
    tipo = 'Não encontrado'
print('Tipo de publicação:', tipo)

Tipo de publicação: Review., Review.

##### 6) Resumo

In [ ]:
try:
    resumo = driver.find_element(By.ID, 'eng-abstract').text
except:
    try:
        resumo = driver.find_element(By.CLASS_NAME, 'abstract-content').text
    except:
        resumo = 'Resumo não disponível'
print('Resumo:', resumo[:500] + '...' if len(resumo) > 500 else resumo)

##### 7) Link de acesso (como registro de referência)

In [ ]:
link_acesso = driver.current_url
print('Link de acesso:', link_acesso)

Link de acesso: https://pubmed.ncbi.nlm.nih.gov/30970133/

In [ ]:
# driver.quit()

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [ ]:
colunas = ['Título', 'Autores', 'Ano', 'DOI', 'Tipo de publicação', 'Resumo', 'Link']
df = pd.DataFrame(columns=colunas)
df

Empty DataFrame
Columns: [Título, Autores, Ano, DOI, Tipo de publicação, Resumo, Link]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [ ]:
# 2) Obter dados de cada link e armazenar na tabela
import re
import time

# Garante que o navegador está aberto (caso tenha sido fechado)
# Se necessário, descomente as linhas abaixo:
# driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

dados = []

for link in lista_de_links:
    driver.get(link)
    time.sleep(1.5)  # pequena pausa para a página carregar

    # Título
    try:
        titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
    except:
        titulo = None

    # Autores
    try:
        autores = driver.find_element(By.CLASS_NAME, 'authors-list').text
    except:
        try:
            autores_els = driver.find_elements(By.CLASS_NAME, 'full-name')
            autores = ', '.join([a.text for a in autores_els])
        except:
            autores = None

    # Ano
    try:
        citacao = driver.find_element(By.CLASS_NAME, 'cit').text
        ano_match = re.search(r'\b(19|20)\d{2}\b', citacao)
        ano = ano_match.group(0) if ano_match else None
    except:
        try:
            ano = driver.find_element(By.CSS_SELECTOR, 'meta[name="citation_publication_date"]').get_attribute('content')
        except:
            ano = None

    # DOI
    try:
        doi = driver.find_element(By.CSS_SELECTOR, 'a[data-ga-action="DOI"]').text.strip()
    except:
        try:
            doi = driver.find_element(By.CSS_SELECTOR, 'meta[name="citation_doi"]').get_attribute('content')
        except:
            doi = None

    # Tipo de publicação
    try:
        tipos = driver.find_elements(By.CLASS_NAME, 'publication-type')
        tipo = ', '.join([t.text for t in tipos]) if tipos else None
    except:
        tipo = None

    # Resumo
    try:
        resumo = driver.find_element(By.ID, 'eng-abstract').text
    except:
        try:
            resumo = driver.find_element(By.CLASS_NAME, 'abstract-content').text
        except:
            resumo = None

    # Link
    link_acesso = driver.current_url

    dados.append({
        'Título': titulo,
        'Autores': autores,
        'Ano': ano,
        'DOI': doi,
        'Tipo de publicação': tipo,
        'Resumo': resumo,
        'Link': link_acesso
    })
    print(f'Coletado: {titulo[:60] if titulo else "sem título"}...')

df = pd.DataFrame(dados)
print(f'\nTotal de artigos coletados: {len(df)}')

Coletado: Irlen syndrome: systematic review and level of evidence anal...
Coletado: Dizziness in a Child With Irlen Syndrome: Differentiating Vi...
Coletado: Dyslexia with and without Irlen syndrome: A study of influen...
Coletado: [The Irlen syndrome--are there pathophysiologic correlates a...
Coletado: Specific visual symptoms and signs of Meares-Irlen syndrome ...
Coletado: Functional magnetic resonance imaging findings in Meares-Irl...
Coletado: Irlen syndrome: expensive lenses for this ill defined syndro...
Coletado: Plasma cholesterol levels and Irlen syndrome: preliminary st...
Coletado: Irlen lenses: a critical appraisal...
Coletado: Optometric correlates of Meares-Irlen syndrome: a matched gr...

Total de artigos coletados: 10

#### 3) Visualizar tabela

In [ ]:
df

,Título,Autores,Ano,DOI,Tipo de publicação,Resumo,Link
0,Irlen syndrome: systematic review and level of...,"Jordan Da Silva Miyasaka 1 , Raphael V Gonzag...",2019,10.1590/0004-282X20190014,"Review., Review., Review.","Background: Scotopic sensitivity syndrome, lat...",https://pubmed.ncbi.nlm.nih.gov/30970133/
1,Dizziness in a Child With Irlen Syndrome: Diff...,"Carrie W Hoppes 1 , Rebecca L Morrell, Laura ...",2019,10.1097/PEP.0000000000000652,"Case Reports, , Clinical Trial., Clinical Trial.",Purpose: A case study of a 12-year-old boy wit...,https://pubmed.ncbi.nlm.nih.gov/31469774/
2,Dyslexia with and without Irlen syndrome: A st...,"Ehab R Abdelraouf 1 2 , Ayman Kilany 1 3...",2022,10.1002/ibra.12080,"Review., Review.",The presence of comorbid Irlen syndrome (IS) i...,https://pubmed.ncbi.nlm.nih.gov/37786524/
3,[The Irlen syndrome--are there pathophysiologi...,"M Döhnert 1 , E D Englert",2003,10.1024/1422-4917.31.4.305,"Review, , Review., Review.",NaN,https://pubmed.ncbi.nlm.nih.gov/14694847/
4,Specific visual symptoms and signs of Meares-I...,"Minwook Chang 1 , Seung-Hyun Kim 1 , Joo-You...",2014,10.3341/kjo.2014.28.2.159,"Review., Review.",Purpose: To discriminate the visual symptoms a...,https://pubmed.ncbi.nlm.nih.gov/24688259/
5,Functional magnetic resonance imaging findings...,"Ji Hyun Kim 1 , Hye-Jin Seo 2 , Suk-Gyu Ha ...",2015,10.3341/kjo.2015.29.2.121,"Review., Review.",Purpose: To investigate patterns of functional...,https://pubmed.ncbi.nlm.nih.gov/25829829/
6,Irlen syndrome: expensive lenses for this ill ...,Gwyn Samuel Williams,2014,10.1136/bmj.g4872,"Review., Review.",NaN,https://pubmed.ncbi.nlm.nih.gov/25239616/
7,Plasma cholesterol levels and Irlen syndrome: ...,"D L Sparkes 1 , G L Robinson, H Dunstan, T K ...",2003,10.2466/pms.2003.97.3.743,"Clinical Trial., Review., Review.",The preliminary study investigated metabolic a...,https://pubmed.ncbi.nlm.nih.gov/14738334/
8,Irlen lenses: a critical appraisal,"H A Solan 1 , J Richman",1990,,"Review, , Review., Clinical Trial., Review.",The purpose of this paper is to assess the cre...,https://pubmed.ncbi.nlm.nih.gov/2136527/
9,Optometric correlates of Meares-Irlen syndrome...,"B J Evans 1 , A Busby, R Jeanes, A J Wilkins",1995,10.1046/j.1475-1313.1995.9500063j.x,Review.,People who report visual perceptual distortion...,https://pubmed.ncbi.nlm.nih.gov/8524579/

#### 4) Exportar DataFrame para Excel

In [ ]:
# 4) Exportar DataFrame para Excel
df.to_excel('pubmed_irlen_syndrome.xlsx', index=False)
print('Arquivo exportado: pubmed_irlen_syndrome.xlsx')

# Fechar o navegador ao final
driver.quit()